server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name ente.me.internal;

    include /etc/nginx/snippets/security.conf;

    location / {
        proxy_pass http://ente-web:3000;

        include /etc/nginx/snippets/proxy.conf;
    }
}
