server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name technitium.me.internal;

    include /etc/nginx/snippets/security.conf;

    location / {
        proxy_pass http://technitium:5380;

        include /etc/nginx/snippets/proxy.conf;
    }
}
